spring.application.name=telemetry-services
server.port=8092
spring.session.store-type=none
# CORS Configuration
app.cors.allowed-origins=http://localhost:4200
app.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
app.cors.allowed-headers=*
## =====================================================================
## INTEGRAZIONE CON CONFIG SERVER VIA EUREKA
## =====================================================================
eureka.client.service-url.defaultZone=http://service-registry:8761/eureka/

## =====================================================================
## MONGO DB
## =====================================================================
spring.mongodb.uri=${MONGODB_URI}

#Connessione cloudamqp
spring.rabbitmq.host=${RABBITMQ_HOST}
spring.rabbitmq.port=${RABBITMQ_PORT}
spring.rabbitmq.username=${RABBITMQ_USERNAME}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}
spring.rabbitmq.virtual-host=${RABBITMQ_VHOST}
spring.rabbitmq.ssl.enabled=true
#lettura eventi
telemetry.rabbitmq.queue=telemetry.event.queue
#Invio comandi
telemetry.rabbitmq.exchange=drone.commands.exchange
telemetry.rabbitmq.routing-key=drone.command
# Abilita la conferma dell'invio (ACK/NACK) dal broker RabbitMQ
spring.rabbitmq.publisher-confirm-type=correlated

telemetry.perimeter.threshold-km=5
telemetry.battery.critical-threshold=20

## =====================================================================
## Resilience4j
#  Se tra le ultime 10 chiamate registrate nella finestra (50%) falliscono, l'interruttore si apre e blocca le successive comunicazioni.
## =====================================================================
resilience4j.circuitbreaker.instances.commandPublisher.slidingWindowType=COUNT_BASED
resilience4j.circuitbreaker.instances.commandPublisher.slidingWindowSize=5
resilience4j.circuitbreaker.instances.commandPublisher.failureRateThreshold=50.0
resilience4j.circuitbreaker.instances.commandPublisher.waitDurationInOpenState=10000ms
#Il numero di chiamate di prova consentite quando si passa allo stato HALF_OPEN
resilience4j.circuitbreaker.instances.commandPublisher.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.instances.commandPublisher.automaticTransitionFromOpenToHalfOpenEnabled=true
# Cattura sia le eccezioni di Spring AMQP che quelle del client nativo RabbitMQ
resilience4j.circuitbreaker.instances.commandPublisher.recordExceptions[0]=java.lang.Exception
resilience4j.circuitbreaker.instances.commandPublisher.ignoreExceptions[0]=java.lang.IllegalArgumentException